backend:
  name: git-gateway
  branch: master
media_folder: "static/img/uploads"
public_folder: "/img/uploads"
collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        required: false
        widget: "datetime"
      - label: "Categories"
        name: "categories"
        required: false
        widget: "list"
      - label: "Tags"
        name: "tags"
        widget: "list"
        allow_add: true
        default: ["news"]
        options: ["news","tips", "datos", "natuuraleza","laguna"]
      - label: "Cover Image"
        name: "image"
        required: false
        widget: "image"
      - label: "Body"
        name: "body"
        widget: "markdown"